### ISSUE TITLE
sanitize_windows.go:61:15: undefined: strings.Builder

### ISSUE THREAD

**Issue by machine-uprising** [whyrusleeping/tar-utils#4]
Following the instructions @ https://github.com/ipfs/go-ipfs/blob/master/docs/windows.md#minimal I got this message when running _go get -u github.com/whyrusleeping/gx_ and ..../gx-go.

Message:
**sanitize_windows.go:61:15: undefined: strings.Builder**

Any ideas? Cheers

**Comment by djdv** [comment]
This was introduced in Go 1.10 so you must update Go.
https://golang.org/doc/go1.10#strings

**Comment by machine-uprising** [comment]
Thanks djdv that fixed it. Closing Issue
